### ISSUE TITLE
Bug: 프로젝트 카드 (Small Card) 텍스트 이슈

### ISSUE THREAD

**Issue by Olivia-SY129** [project-matching/project-matching-frontend#17]
글자 수가 카드를 넘어갈 경우 카드 크기가 변함.
어떻게 수정할 지 논의 필요 @dobbyyo 
지원 포지션 개수를 고려하여 수정하기
- 기술 스택은 최상단 3개만 노출

**Comment by dobbyyo** [comment]
넵 생각해서 말씀드리겠습니다.

**Comment by Olivia-SY129** [comment]
- 텍스트 초과 시 mouse hover로 추가 정보 표시
