### ISSUE TITLE
feat: post details page 구현 필요한 부분들

### ISSUE THREAD

**Issue by younchong** [project-matching/project-matching-frontend#69]
* - [x] 댓글 입력창 (댓글 적히면 받아오는 데, 유저들이 입력하는 부분을 피그마에서 확인못해서 나중에 봐야겠다 하다가 빼둔 것 같습니다) (승연님)
* - [x] 관리자 모드 시,  추방 버튼 (추방 모달과 거절 모달이 같이 사용될 것이라고 생각돼서 이전 모달 문제로 미루어두었습니다.) (본인)
* - [x] 멤버 모드시, 탈퇴하기 버튼 (본인)
* - [x] 일반 유저가 프로젝트 신청이후 다른 포지션 신청 막아두기 (승연님)
* - [x] 수정된 모달로 설정하기

**Comment by Olivia-SY129** [comment]
- fix: 댓글 리스트 페이지네이션 필요, 댓글 전체 개수 표시

**Comment by younchong** [comment]
모두 완료
