### ISSUE TITLE
fix: 댓글 페이지네이션, 댓글 갯수

### ISSUE THREAD

**Issue by younchong** [project-matching/project-matching-frontend#78]
<img width="579" alt="스크린샷 2022-09-28 오후 3 55 28" src="https://user-images.githubusercontent.com/78673049/192709587-99c67538-014f-4bb5-a8d9-91e4ad3745dd.png">

<img width="1440" alt="스크린샷 2022-09-28 오후 3 54 59" src="https://user-images.githubusercontent.com/78673049/192709614-8dbd23f1-428e-41b9-96ef-1a9260dd9c4b.png">

* comment가 5개씩만 불러오는 것 같습니다.
* 페이징을 넣어서 가져오는 것 같은데 뒤에 넣고 해봤는데 에러가 생겨서 어디에 적어야하는지 모르겠습니다.

**Comment by Olivia-SY129** [comment]
해당 이슈가 혹시 백엔드 이슈인가요? 쿼리에 page={number} 를 추가하시면 동작할 것 같습니다. 다른 페이지네이션 코드를 참고해주세요.

**Comment by younchong** [comment]
pageNumber={number}로 해봤었는데, 말씀하신 방법으로 시도해보고 말씀드리겠습니다. 감사합니다.
